### ISSUE TITLE
How should scheduling work? 

### ISSUE THREAD

**Issue by RusseII** [alwaysbegrowing/fokus#3]
There are a few ways we can handle scheduling - I'd recommend not spending too much time thinking / discussing the different options and just building one. This is something that we can easily modify in the future.  

1. Focumate.com style where you manually schedule every session 
2. Schedule based where you pick your schedule and auto have sessions 
3. Cal.com style - every1 has a personal link 

I think we should also restrict the times that people can book while we are starting out to ensure a higher match rate 

# Personal Preferences 
The best experience for me would be if I had 8 FMs per day at my predefined times. I'd also want the ability to cancel sessions if I have a conflict IRL. 
People prefrences?
I like having varity to who I book with. So rotating between lucky nam and bookcliff is preferable to b2b2b2b sessions with one person. I COULD have fun with different models though. Like all my sessions with lucky on one day, all sessions with nam on another, etc 

# Proposal (accepted) 
I propose we start with number 1. I'm imagining a UI similar to 
<img width="927" alt="CleanShot 2022-07-05 at 13 58 58@2x" src="https://user-images.githubusercontent.com/15036618/177397007-4b4bfcd7-ae02-4ac8-9e39-7d599c220e10.png"> that shows either an entire week or individual days. We start out limiting the sessions to 8 possible times, with us bootstrapping them. We can guarantee that new users get a partner 100% of the time if we do this. Later we could add an option like "book indefinitely", but thats more of an advanced feature. I think the first focusmate for users is high friction so it'd be helpful to make creating the first session as easy and simple as possible

# Technical 
I'd advocate for the simplest solution for the scheduling starting out. 

We must keep the following thoughts in mind: 
1. We should restrict the available times that users can book. This allows us to ensure that our early users are all matched with partners
2. We should provide a backstop to ensure that our early users always get matched with someone. It's a very bad experience to sign up for a session and not get a partner. We can design this system in a way that it's always @RusseII @Geczy or @Namaskar-1F64F get left without a partner 
3. We should design it in a way where the 3 of us matched with new users if possible so we can ensure they have a good first session

## Implementation 
1. [MongoDB Vercel Plugin](https://vercel.com/integrations/mongodbatlas)
2. Think through the needed entities and their relationships

### Ideas 
Users have sessions 
Sessions have users 
Each user has a list of their sessions 
Each session is a separate entity with time, participant, 
```


// show all of the users booked sessions 
// show who the session are booked with (potentially) 
// allow users to cancel sessions 
// allow for booking up to 1 week in the future
// allow booking indefinitely into the future ...? coming soon? 

When a user books a session store it as {
  user: address,
  time: time&date
  match: matchAddress
 }
```

check if there are any empty matches at the same time when booking - if there is, set them as a match and update the other person to match with them
When a user cancels a session - cancel both the session getting canceled and null out the match field for the user they were matched with

**Comment by RusseII** [comment]
@Geczy @Namaskar-1F64F @Bookcliff @gatesyp what does the ideal scheduling experience look like for you?

**Comment by Geczy** [comment]
sounds fine, can we still leverage cal.com?

**Comment by RusseII** [comment]
> sounds fine, can we still leverage cal.com?

For just the scheduling? Maybe - haven't looked into it too much yet

**Comment by Geczy** [comment]
scheduling is kinda figured out now, we will be leveraging calcom

the matching algorithm still has to be developed, but it will essentially just call the `book` function from calcom on two people
